import {PAGE_LOCALES,validatePageDocument} from './schema.mjs';
import {BLOCK_DEFINITIONS} from './block-definitions.mjs';
import {normalizePageSlug,reservedPageSlug} from './routes.mjs';
import {createPageValidators} from '../azura-page-content-validation.mjs';
export class DynamicPageError extends Error {constructor(message,status=400){super(message);this.status=status;}}
const {keys}=createPageValidators('dynamic',DynamicPageError);
const ID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function validatePageId(id){if(typeof id!=='string'||!ID.test(id))throw new DynamicPageError('Geçersiz kalıcı sayfa kimliği.');}
function text(v){if(typeof v!=='string'||v.length>100000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))throw new DynamicPageError('Geçersiz metin.');}
function bool(v){if(typeof v!=='boolean')throw new DynamicPageError('Boolean gerekli.');}
function date(v){if(typeof v!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString()!==v)throw new DynamicPageError('Geçersiz tarih.');}
export function validateDynamicImage(v){if(typeof v!=='string'||(v!==''&&(!/^\/uploads\/dynamic-pages\/[A-Za-z0-9][A-Za-z0-9._-]{0,127}\.(jpg|jpeg|png|webp)$/i.test(v)||v.includes('..'))))throw new DynamicPageError('Geçersiz dinamik sayfa görseli.');}
export function validateDynamicHref(v){text(v);if(!v)return;if(v!==v.trim()||/[\\\s\u0000-\u001f]/.test(v)||/%(?:0[0-9a-f]|1[0-9a-f]|7f|5c)/i.test(v))throw new DynamicPageError('Güvensiz bağlantı.');if(v.startsWith('/')&&!v.startsWith('//'))return;if(/^#[A-Za-z0-9_-]+$/.test(v))return;try{const u=new URL(v);if(v.startsWith('https://')&&u.protocol==='https:'&&!u.username&&!u.password)return;}catch{}throw new DynamicPageError('Bağlantı yalnız yerel yol, #anchor veya HTTPS olabilir.');}
function translations(value,fields){keys(value,PAGE_LOCALES,'translations');for(const l of PAGE_LOCALES){keys(value[l],fields,l);for(const f of fields){text(value[l][f]);if(f==='buttonHref')validateDynamicHref(value[l][f]);}}}
function collection(items,kind){if(!Array.isArray(items))throw new DynamicPageError('Koleksiyon dizi olmalı.');const ids=new Set(),orders=new Set();for(const r of items){const imageKind=kind==='imageArray';const fields=imageKind?['imageAlt']:kind==='cardArray'?['title','text','imageAlt','buttonText','buttonHref']:['eyebrow','title','size','capacity','text','imageAlt','buttonHref'];keys(r,['id',imageKind?'src':'image','order','translations'],'collection');if(typeof r.id!=='string'||!r.id||r.id.length>128||ids.has(r.id))throw new DynamicPageError('Koleksiyon kimliği geçersiz.');ids.add(r.id);if(!Number.isSafeInteger(r.order)||r.order<0||orders.has(r.order))throw new DynamicPageError('Koleksiyon sırası geçersiz.');orders.add(r.order);validateDynamicImage(r[imageKind?'src':'image']);if(imageKind&&!r.src)throw new DynamicPageError('Görsel kaynağı gerekli.');translations(r.translations,fields);}}
export function validateDynamicDocument(p,id,status){
 const errors=validatePageDocument(p);if(errors.length)throw new DynamicPageError(errors.join(' '));
 keys(p,['id','schemaVersion','template','slugs','status','showContactSection','hero','navigation','seo','sections','createdAt','updatedAt'],'page');if(p.id!==id||p.status!==status)throw new DynamicPageError('Sayfa kimliği/durumu uyuşmuyor.');date(p.createdAt);date(p.updatedAt);bool(p.showContactSection);keys(p.slugs,PAGE_LOCALES,'slugs');for(const l of PAGE_LOCALES){if(normalizePageSlug(p.slugs[l],l)!==p.slugs[l]||reservedPageSlug(p.slugs[l],l))throw new DynamicPageError('Normalleştirilmemiş veya ayrılmış slug.');}
 keys(p.hero,['image','overlay','translations'],'hero');validateDynamicImage(p.hero.image);bool(p.hero.overlay);translations(p.hero.translations,['eyebrow','title','imageAlt']);
 keys(p.navigation,['visible','order','translations'],'navigation');bool(p.navigation.visible);if(!Number.isFinite(p.navigation.order))throw new DynamicPageError('Menü sırası geçersiz.');translations(p.navigation.translations,['label']);translations(p.seo,['title','description']);
 for(const s of p.sections){const def=BLOCK_DEFINITIONS[s.type];const local=def.fields.filter(f=>f.localized).map(f=>f.name),shared=def.fields.filter(f=>!f.localized);keys(s,['id','type','enabled','translations',...shared.map(f=>f.name),...(Object.hasOwn(s,'variant')?['variant']:[])],'section');bool(s.enabled);if(s.variant!==undefined&&!def.variants.some(v=>v.id===s.variant))throw new DynamicPageError('Bilinmeyen varyant.');translations(s.translations,local);for(const f of shared){const v=s[f.name];if(f.type==='image')validateDynamicImage(v);else if(f.type==='boolean')bool(v);else if(f.type==='select'){if(!f.options.some(o=>o.value===v))throw new DynamicPageError('Geçersiz varyant alanı.');}else collection(v,f.type);}}
 return p;
}
export function validateDynamicRecord(r,id){validatePageId(id);keys(r,['storageVersion','id','createdAt','updatedAt','publishedAt','history','draft','published'],'record');if(r.storageVersion!==2||r.id!==id)throw new DynamicPageError('Geçersiz v2 kayıt.');date(r.createdAt);date(r.updatedAt);if(r.publishedAt!==null)date(r.publishedAt);if((r.published===null)!==(r.publishedAt===null))throw new DynamicPageError('Yayın tarihi uyuşmuyor.');validateDynamicDocument(r.draft,id,'draft');if(r.published!==null)validateDynamicDocument(r.published,id,'published');if(!Array.isArray(r.history))throw new DynamicPageError('Geçersiz geçmiş.');const ids=new Set();for(const h of r.history){keys(h,['versionId','createdAt','action','createdBy','wasPublished','draft'],'history');validatePageId(h.versionId);if(ids.has(h.versionId)||h.action!=='draft-save')throw new DynamicPageError('Geçersiz geçmiş kimliği/işlemi.');ids.add(h.versionId);date(h.createdAt);bool(h.wasPublished);if(h.createdBy!==null){keys(h.createdBy,['id','username','displayName','role'],'actor');Object.values(h.createdBy).forEach(text);}validateDynamicDocument(h.draft,id,'draft');}return r;}
export function dynamicImages(page){const out=[page.hero.image];for(const s of page.sections){const d=BLOCK_DEFINITIONS[s.type];for(const f of d.fields.filter(f=>!f.localized)){if(f.type==='image')out.push(s[f.name]);else if(['imageArray','cardArray','otherOptionArray'].includes(f.type))out.push(...s[f.name].map(r=>r.src??r.image));}}return [...new Set(out.filter(Boolean))];}
