import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {listMediaLibrary,reuseLibraryImage} from './azura-media-library.mjs';
test('library scopes, filtering, safe decoding, deduplication, concurrency and content isolation',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'azura-library-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const paths={contentRoot:path.join(root,'content'),uploadsRoot:path.join(root,'uploads')};
 for(const dir of ['pages/homepage','pages/rooms','pages/room-options','blog','gallery','dynamic-pages'])await mkdir(path.join(paths.uploadsRoot,dir),{recursive:true});
 await mkdir(paths.contentRoot);await writeFile(path.join(paths.contentRoot,'untouched.json'),' {"user":"unchanged"} ');
 const bytes=await sharp({create:{width:40,height:30,channels:3,background:'red'}}).png().toBuffer();
 const source=path.join(paths.uploadsRoot,'pages/homepage/source.png');await writeFile(source,bytes);
 await writeFile(path.join(paths.uploadsRoot,'pages/homepage/.hidden.png'),bytes);
 await writeFile(path.join(paths.uploadsRoot,'pages/homepage/source.png.bak'),bytes);
 await writeFile(path.join(paths.uploadsRoot,'pages/homepage/data.json'),'{}');
 await writeFile(path.join(paths.uploadsRoot,'pages/homepage/fake.png'),'not png');
 await symlink(source,path.join(paths.uploadsRoot,'pages/homepage/link.png'));
 await writeFile(path.join(paths.uploadsRoot,'pages/room-options/preview.png'),bytes);
 const all=await listMediaLibrary(undefined,paths);assert.equal(all.total,2);assert.equal(all.images[0].width,40);
 const page=await listMediaLibrary(new URLSearchParams('limit=1'),paths);assert.equal(page.nextOffset,1);
 assert.equal((await listMediaLibrary(new URLSearchParams('q=source&scope=homepage'),paths)).total,1);
 for(const q of ['folder=..','limit=101','limit=0','offset=-1','scope=unknown','limit=2&limit=3'])await assert.rejects(listMediaLibrary(new URLSearchParams(q),paths));
 const image='/uploads/pages/homepage/source.png';
 assert.equal((await reuseLibraryImage({image,targetScope:'homepage'},paths)).status,200);
 const before=await readFile(source);
 const results=await Promise.all(Array.from({length:5},()=>reuseLibraryImage({image,targetScope:'blog'},paths)));
 assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(new Set(results.map(r=>r.body.image)).size,1);
 assert.deepEqual(await readFile(path.join(paths.uploadsRoot,results[0].body.image.slice('/uploads/'.length))),bytes);
 await writeFile(path.join(paths.uploadsRoot,'pages/rooms/custom.png'),bytes);
 const reused=await reuseLibraryImage({image,targetScope:'rooms'},paths);assert.equal(reused.status,200);assert.equal(reused.body.image,'/uploads/pages/rooms/custom.png');
 assert.equal((await reuseLibraryImage({image:'/uploads/pages/room-options/preview.png',targetScope:'gallery'},paths)).status,201);
 for(const input of [{image,targetScope:'room-options'},{image,targetScope:'../x'},{image:'https://example.com/a.png',targetScope:'blog'},{image:'/uploads/pages/homepage/../x.png',targetScope:'blog'},{image:'/uploads/pages/homepage/link.png',targetScope:'blog'},{image:'/uploads/pages/homepage/fake.png',targetScope:'blog'},{image,targetScope:'blog',extra:true}])await assert.rejects(reuseLibraryImage(input,paths));
 await writeFile(path.join(paths.uploadsRoot,'pages/homepage/large.png'),Buffer.alloc(8*1024*1024+1));
 await assert.rejects(reuseLibraryImage({image:'/uploads/pages/homepage/large.png',targetScope:'blog'},paths));
 await writeFile(path.join(paths.uploadsRoot,'pages/homepage/pixels.png'),await sharp({create:{width:4001,height:4000,channels:3,background:'red'}}).png().toBuffer());
 await assert.rejects(reuseLibraryImage({image:'/uploads/pages/homepage/pixels.png',targetScope:'blog'},paths));
 await symlink(path.join(paths.uploadsRoot,'pages/homepage'),path.join(paths.uploadsRoot,'pages/bars'));
 await assert.rejects(listMediaLibrary(new URLSearchParams('scope=bars'),paths));
 assert.deepEqual(await readFile(source),before);assert.equal(await readFile(path.join(paths.contentRoot,'untouched.json'),'utf8'),' {"user":"unchanged"} ');
});
